### ISSUE TITLE
Failed to start erigon using Docker compose，help

### ISSUE THREAD

**Issue by backApril** [node-real/bsc-erigon#660]
**bsc-erigon branch：main(latest)**

**.env**
```
ERIGON_USER=erigon
XDG_DATA_HOME=~erigon/.ethereum

DOCKER_UID=1001     # random number [1001, 10000] chosen arbitrarily for example
DOCKER_GID=1001     # can choose any valid #. 1000 tends to be taken by first user
```

**docker-compose.yml**

```
x-erigon-service: &default-erigon-service
  image: erigontech/erigon:${TAG:-latest}
  pid: service:erigon # Use erigon's PID namespace. It's required to open Erigon's DB from another process (RPCDaemon local-mode)
  volumes_from: [ erigon ]
  restart: unless-stopped
  mem_swappiness: 0
  user: ${DOCKER_UID:-1000}:${DOCKER_GID:-1000}

services:
  erigon:
    image: erigontech/erigon:${TAG:-latest}
    build:
      args:
        UID: ${DOCKER_UID:-1000}
        GID: ${DOCKER_GID:-1000}
      context: .
    command: |
      ${ERIGON_FLAGS-} --private.api.addr=0.0.0.0:9090
      --txpool.disable
      --http.api=eth,erigon,web3,net,debug,trace,txpool
      --metrics --metrics.addr=0.0.0.0 --metrics.port=6060 --pprof --pprof.addr=0.0.0.0 --pprof.port=6061
      --authrpc.jwtsecret=/home/erigon/.local/share/erigon/jwt.hex --datadir=/home/erigon/.local/share/erigon
      --prune.mode=archive --prune.distance.blocks=90000 --prune.distance=90000 --db.pagesize=4kb
      --chain=bsc
      --networkid=56
    ports: 
      - "8551:8551"
    volumes:
      - ${XDG_DATA_HOME:-~/.local/share}/erigon:/home/erigon/.local/share/erigon
    restart: unless-stopped
    mem_swappiness: 0
    user: ${DOCKER_UID:-1000}:${DOCKER_GID:-1000}

  sentry:
    <<: *default-erigon-service
    entrypoint: sentry
    command: ${SENTRY_FLAGS-} --sentry.api.addr=0.0.0.0:9091 --datadir=/home/erigon/.local/share/erigon
    ports: [ "30303:30303/tcp", "30303:30303/udp" ]

  downloader:
    <<: *default-erigon-service
    entrypoint: downloader
    command: ${DOWNLOADER_FLAGS-} --downloader.api.addr=0.0.0.0:9093 --datadir=/home/erigon/.local/share/erigon
    ports: [ "42069:42069/tcp", "42069:42069/udp" ]

  txpool:
    <<: *default-erigon-service
    entrypoint: txpool
    command: ${TXPOOL_FLAGS-} --private.api.addr=erigon:9090 --txpool.api.addr=0.0.0.0:9094 --sentry.api.addr=sentry:9091 --datadir=/home/erigon/.local/share/erigon

  rpcdaemon:
    <<: *default-erigon-service
    entrypoint: rpcdaemon
    command: |
      ${RPCDAEMON_FLAGS-} --http.addr=0.0.0.0 --http.vhosts=any --http.corsdomain=* --ws
      --private.api.addr=erigon:9090 --txpool.api.addr=txpool:9094 --datadir=/home/erigon/.local/share/erigon
    ports: [ "8545:8545","8546:8546" ]

  prometheus:
    image: prom/prometheus:v2.51.2
    user: ${DOCKER_UID:-1000}:${DOCKER_GID:-1000} # Uses erigon user from Dockerfile
    command: --log.level=warn --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus --storage.tsdb.retention.time=150d --web.console.libraries=/usr/share/prometheus/console_libraries --web.console.templates=/usr/share/prometheus/consoles
    ports: [ "9090:9090" ]
    volumes:
      - ${ERIGON_PROMETHEUS_CONFIG:-./cmd/prometheus/prometheus.yml}:/etc/prometheus/prometheus.yml
      - ${XDG_DATA_HOME:-~/.local/share}/erigon-prometheus:/prometheus
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.4.2
    user: "${DOCKER_UID:-1000}:${DOCKER_GID:-1000}"
    ports: [ "3000:3000" ]
    volumes:
      - ${ERIGON_GRAFANA_CONFIG:-./cmd/prometheus/grafana.ini}:/etc/grafana/grafana.ini
      - ./cmd/prometheus/datasources:/etc/grafana/provisioning/datasources
      - ./cmd/prometheus/dashboards:/etc/grafana/provisioning/dashboards
      - ${XDG_DATA_HOME:-~/.local/share}/erigon-grafana:/var/lib/grafana
    restart: unless-stopped
```

**docker erigon logs**

```
erigon-1  | [INFO] [04-02|04:53:33.007] logging to file system                   log dir=/home/erigon/.local/share/erigon/logs file prefix=erigon log level=info json=false
erigon-1  | [INFO] [04-02|04:53:33.007] Enabling metrics export to prometheus    path=http://0.0.0.0:6060/debug/metrics/prometheus
erigon-1  | [INFO] [04-02|04:53:33.007] Starting pprof server                    cpu="go tool pprof -lines -http=: http://0.0.0.0:6061/debug/pprof/profile?seconds=20" heap="go tool pprof -lines -http=: http://0.0.0.0:6061/debug/pprof/heap"
erigon-1  | [INFO] [04-02|04:53:33.007] Build info                               git_branch=release/3.0 git_tag=v3.0.0 git_commit=57625b40faa6f2c821e3d577f0fb70bca1b705bf
erigon-1  | [INFO] [04-02|04:53:33.007] Starting Erigon on                       devnet=bsc
erigon-1  | [WARN] [04-02|04:53:33.007] No snapshot hashes for chain             chain=bsc
erigon-1  | [INFO] [04-02|04:53:33.008] Maximum peer count                       total=32
erigon-1  | [INFO] [04-02|04:53:33.008] starting HTTP APIs                       port=8545 APIs=eth,erigon,web3,net,debug,trace,txpool
erigon-1  | [EROR] [04-02|04:53:33.009] catch panic                              err="runtime error: invalid memory address or nil pointer dereference" stack="[main.go:46 panic.go:791 panic.go:262 signal_unix.go:917 flags.go:1722 flags.go:1942 node.go:123 main.go:96 make_app.go:71 command.go:276 app.go:333 app.go:307 main.go:51 proc.go:272 asm_amd64.s:1700]"
```
What went wrong? It didn't run
